### ISSUE TITLE
Depedencies incorrectly installed with "pip install ."

### ISSUE THREAD

**Issue by wanghch123** [DuskNgai/plunet#1]
After running `pip install .`, verison of PyTorch which automatically installed is 2.0.1+cpu with no cuda. Is there any problem with your "pyproject.toml"?

**Comment by DuskNgai** [comment]
I apologize for the inconvenience. My intention was to avoid conflicts between lower versions of the nVidia driver and higher versions of PyTorch. I have fixed this problem and updated "pyproject.toml" and "install.md". Please check and comment! Very very very much appreciated!
